name: tonatona-websockets
version: "0.1.0.0"
category: Library
# synopsis:
# description:
license: "MIT"
author: Tomone Akashi
copyright: 2021 Tomone Akashi
maintainer: akashiz2224@gmail.com

extra-source-files:
  - README.md

ghc-options: -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 4.15
  - data-default >= 0.7 && < 0.8
  - exceptions >= 0.8 && < 0.11
  - http-types >= 0.12 && < 0.13
  - monad-logger >= 0.3 && < 0.4
  - rio >= 0.1 && < 0.2
  - servant >= 0.13 && < 0.17
  - servant-server >= 0.13 && < 0.17
  - tonaparser >= 0.1 && < 0.2
  - tonatona >= 0.1 && < 0.2
  - tonatona-logger >= 0.1 && < 0.3
  - tonatona-servant >= 0.1 && < 0.2
  - wai >= 3.2 && < 3.3
  - wai-websockets >= 3.0 && < 3.1
  - websockets >= 0.12 && < 0.13
  - wai >= 3.2 && < 3.3
  - wai-extra >= 3.0.27 && < 3.1
  - warp >= 3.2 && < 3.4

library:
  source-dirs:
    - src
  exposed-modules:
    - Tonatona.Servant.WebSockets
    - Tonatona.Wai.WebSockets
    - Tonatona.WebSockets

tests:
  spec:
    main: "Spec.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - tonatona-websockets
      - hspec
      - QuickCheck
  doctest:
    main: "DocTest.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - tonatona-websockets
      - doctest
      - Glob

github: qnoyxu/tonatona-websockets
